'use strict';

/* Services */

var flightServices = angular.module('flightServices', ['ngResource']);

flightServices.factory('FlightService',
    function($q, $http){
        var param = {}

        function formatDate(date) {
            var d = new Date(date),
                month = '' + (d.getMonth() + 1),
                day = '' + d.getDate(),
                year = d.getFullYear();

            if (month.length < 2) month = '0' + month;
            if (day.length < 2) day = '0' + day;

            return [year, month, day].join('-');
        }

        function getFlightRequests() {
            var deferred = $q.defer();
            console.info("http://94.23.63.229:3000/flight/research?ddate=" + formatDate(param.ddate) + "&adate=" + formatDate(param.adate) +
            "&dcity=" + param.dcity.flag + "&acity=" + param.acity.flag + "&flightway=" + param.flightway + "&seatclass=" + param.seatclass +
            "&adult=" + param.adult + "&child=" + param.child + "&nonstoponly=" + param.nonstoponly);

            $http({
                method: 'GET',
                url: "http://localhost:3000/flight/research?ddate=" + formatDate(param.ddate) + "&adate=" + formatDate(param.adate) +
                "&dcity=" + param.dcity.flag + "&acity=" + param.acity.flag + "&flightway=" + param.flightway + "&seatclass=" + param.seatclass +
                "&adult=" + param.adult + "&child=" + param.child + "&nonstoponly=" + param.nonstoponly
            }).success(function (response) {
                deferred.resolve(response);
            }).error(function (error) {
                deferred.reject(error);
            });

            return deferred.promise;
        }

        function setData(data) {
            param = data;
        }

        function getData() {
            return param;
        }

        return {
            getFlightRequests: getFlightRequests,
            setData : setData,
            getData : getData
        }

    });

flightServices.factory('IATAService',
    function(){
        function getIATAJson() {
            return [{'name':'安徽省 安庆 天柱山机场','flag':'AQG'},
                {'name':'安徽省 池州 九华山机场','flag':'JUH'},
                {'name':'安徽省 阜阳 西关机场','flag':'FUG'},
                {'name':'安徽省 合肥 新桥国际机场','flag':'HFE'},
                {'name':'安徽省 黄山 屯溪机场','flag':'TXN'},
                {'name':'北京 北京南苑 南苑国际机场','flag':'NAY'},
                {'name':'北京 北京首都 首都国际机场','flag':'PEK'},
                {'name':'福建省 福州 长乐国际机场','flag':'FOC'},
                {'name':'福建省 晋江 晋江国际机场','flag':'JJN'},
                {'name':'福建省 连城 连城机场','flag':'LCX'},
                {'name':'福建省 武夷山 武夷山机场','flag':'WUS'},
                {'name':'福建省 厦门 高崎国际机场','flag':'XMN'},
                {'name':'甘肃省 酒泉 酒泉机场','flag':'CHW'},
                {'name':'甘肃省 敦煌 敦煌机场','flag':'DNH'},
                {'name':'甘肃省 庆阳 西峰镇机场','flag':'IQN'},
                {'name':'甘肃省 嘉峪关 嘉峪关机场','flag':'JGN'},
                {'name':'甘肃省 兰州 中川国际机场','flag':'LHW'},
                {'name':'广东省 广州 白云国际机场','flag':'CAN'},
                {'name':'广东省 佛山 沙堤机场','flag':'FUO'},
                {'name':'广东省 梅县 梅县机场','flag':'MXZ'},
                {'name':'广东省 揭阳/汕头 揭阳潮汕机场','flag':'SWA'},
                {'name':'广东省 深圳 宝安国际机场','flag':'SZX'},
                {'name':'广东省 湛江 湛江机场','flag':'ZHA'},
                {'name':'广东省 珠海 三灶机场','flag':'ZUH'},
                {'name':'广西 北海 福城机场','flag':'BHY'},
                {'name':'广西 桂林 两江国际机场','flag':'KWL'},
                {'name':'广西 柳州 白莲机场','flag':'LZH'},
                {'name':'广西 南宁 吴圩国际机场','flag':'NNG'},
                {'name':'广西 梧州 长洲岛机场','flag':'WUZ'},
                {'name':'贵州省 兴义 兴义机场','flag':'ACX'},
                {'name':'广西省 百色 田阳机场','flag':'AEB'},
                {'name':'贵州省 贵阳 龙洞堡国际机场','flag':'KWE'},
                {'name':'贵州省 铜仁 大兴机场','flag':'TEN'},
                {'name':'贵州省 遵义 遵义机场','flag':'ZYI'},
                {'name':'贵州省 黎平 黎平机场','flag':'HZH'},
                {'name':'贵州省 安顺 黄果树机场','flag':'AVA'},
                {'name':'海南省 海口 美兰国际机场','flag':'HAK'},
                {'name':'海南省 三亚 凤凰国际机场','flag':'SYX'},
                {'name':'河北省 邯郸 邯郸机场','flag':'HDG'},
                {'name':'河北省 秦皇岛 山海关机场','flag':'SHP'},
                {'name':'河北省 石家庄 正定机场','flag':'SJW'},
                {'name':'河南省 安阳 安阳机场','flag':'AYN'},
                {'name':'河南省 郑州 新郑国际机场','flag':'CGO'},
                {'name':'河南省 洛阳 北郊机场','flag':'LYA'},
                {'name':'河南省 南阳 姜营机场','flag':'NNY'},
                {'name':'黑龙江省 大庆 萨尔图机场','flag':'DQA'},
                {'name':'黑龙江省 黑河 黑河机场','flag':'HEK'},
                {'name':'黑龙江省 哈尔滨 太平国际机场','flag':'HRB'},
                {'name':'黑龙江省 佳木斯 东郊机场','flag':'JMU'},
                {'name':'黑龙江省 牡丹江 海浪机场','flag':'MDG'},
                {'name':'黑龙江省 齐齐哈尔 三家子机场','flag':'NDG'},
                {'name':'湖北省 恩施 许家坪机场','flag':'ENH'},
                {'name':'湖北省 武汉 天河国际机场','flag':'WUH'},
                {'name':'湖北省 襄樊 刘集机场','flag':'XFN'},
                {'name':'湖北省 宜昌 三峡机场','flag':'YIH'},
                {'name':'湖南省 常德 桃花源机场','flag':'CGD'},
                {'name':'湖南省 长沙 黄花国际机场','flag':'CSX'},
                {'name':'湖南省 张家界 荷花机场','flag':'DYG'},
                {'name':'湖南省 怀化-芷江 芷江机场','flag':'HJJ'},
                {'name':'湖南省 永州 零陵机场','flag':'LLF'},
                {'name':'吉林省 长春 龙嘉国际机场','flag':'CGQ'},
                {'name':'吉林省 吉林 二台子机场','flag':'JIL'},
                {'name':'吉林省 通化 通化机场','flag':'TNH'},
                {'name':'江苏省 常州 奔牛机场','flag':'CZX'},
                {'name':'江苏省 连云港 白塔埠国际机场','flag':'LYG'},
                {'name':'江苏省 南京 禄口国际机场','flag':'NKG'},
                {'name':'江苏省 南通 兴东机场','flag':'NTG'},
                {'name':'江苏省 无锡/苏州 苏南国际机场','flag':'WUX'},
                {'name':'江苏省 徐州 观音国际机场','flag':'XUZ'},
                {'name':'江苏省 扬州泰州 扬州泰州机场','flag':'YTY'},
                {'name':'江苏省 盐城 南洋机场','flag':'YNZ'},
                {'name':'江苏省 苏州 光福机场','flag':'SZV'},
                {'name':'江西省 景德镇 罗家机场','flag':'JDZ'},
                {'name':'江西省 井冈山 井冈山机场','flag':'JGS'},
                {'name':'江西省 九江 庐山机场','flag':'JIU'},
                {'name':'江西省 南昌 昌北机场','flag':'KHN'},
                {'name':'江西省 赣州 黄金机场','flag':'KOW'},
                {'name':'辽宁省 鞍山 腾鳌机场','flag':'AOG'},
                {'name':'辽宁省 朝阳 朝阳机场','flag':'CHG'},
                {'name':'辽宁省 长海 大长山岛机场','flag':'CNI'},
                {'name':'辽宁省 丹东 浪头机场','flag':'DDG'},
                {'name':'辽宁省 大连 周水子国际机场','flag':'DLC'},
                {'name':'辽宁省 锦州 小岭子机场','flag':'JNZ'},
                {'name':'辽宁省 沈阳 桃仙国际机场','flag':'SHE'},
                {'name':'吉林省 延吉 朝阳川机场','flag':'YNJ'},
                {'name':'内蒙古 包头 海兰泡机场','flag':'BAV'},
                {'name':'内蒙古 赤峰 土城子机场','flag':'CIF'},
                {'name':'内蒙古 鄂尔多斯 鄂尔多斯机场','flag':'DSN'},
                {'name':'内蒙古 呼和浩特 白塔国际机场','flag':'HET'},
                {'name':'内蒙古 海拉尔 东山机场','flag':'HLD'},
                {'name':'内蒙古 乌兰浩特 乌兰浩特机场','flag':'HLH'},
                {'name':'内蒙古 满洲里 西郊机场','flag':'NZH'},
                {'name':'内蒙古 通辽 通辽机场','flag':'TGO'},
                {'name':'内蒙古 乌海 乌海机场','flag':'WUA'},
                {'name':'内蒙古 锡林浩特 锡林浩特','flag':'XIL'},
                {'name':'内蒙古 阿拉善左旗 巴彦浩特机场','flag':'AXF'},
                {'name':'内蒙古 阿拉善右旗 巴丹吉林机场','flag':'RHT'},
                {'name':'宁夏 银川 河东国际机场','flag':'INC'},
                {'name':'青海省 格尔木 格尔木机场','flag':'GOQ'},
                {'name':'青海省 西宁 曹家堡机场','flag':'XNN'},
                {'name':'山东省 东营 永安机场','flag':'DOY'},
                {'name':'山东省 济宁 曲阜机场','flag':'JNG'},
                {'name':'山东省 青岛 流亭国际机场','flag':'TAO'},
                {'name':'山东省 济南 遥墙国际机场','flag':'TNA'},
                {'name':'山东省 潍坊 文登机场','flag':'WEF'},
                {'name':'山东省 威海 大水泊机场','flag':'WEH'},
                {'name':'山东省 烟台 莱山机场','flag':'YNT'},
                {'name':'山西省 长治 王村机场','flag':'CIH'},
                {'name':'山西省 大同 怀仁机场','flag':'DAT'},
                {'name':'山西省 临汾 乔李机场','flag':'LFQ'},
                {'name':'山西省 太原 武宿机场','flag':'TYN'},
                {'name':'山西省 运城 关公机场','flag':'YCU'},
                {'name':'陕西省 安康 五里铺机场','flag':'AKA'},
                {'name':'陕西省 延安 二十里铺机场','flag':'ENY'},
                {'name':'陕西省 汉中 西关机场','flag':'HZG'},
                {'name':'陕西省 榆林 西沙机场','flag':'UYN'},
                {'name':'陕西省 西安 咸阳国际机场','flag':'XIY'},
                {'name':'上海 上海-浦东 浦东国际机场','flag':'PVG'},
                {'name':'上海 上海-虹桥 虹桥国际机场','flag':'SHA'},
                {'name':'四川省 成都 双流国际机场','flag':'CTU'},
                {'name':'四川省 达县 河市霸机场','flag':'DAX'},
                {'name':'四川省 广元 广元机场','flag':'GNY'},
                {'name':'四川省 九寨沟 黄龙机场','flag':'JZH'},
                {'name':'四川省 泸州 蓝田机场','flag':'LZO'},
                {'name':'四川省 绵阳 南郊机场','flag':'MIG'},
                {'name':'四川省 南充 都尉坝机场','flag':'NAO'},
                {'name':'四川省 攀枝花 攀枝花机场','flag':'PZI'},
                {'name':'四川省 万州 万县机场','flag':'WXN'},
                {'name':'四川省 西昌 青山机场','flag':'XIC'},
                {'name':'四川省 宜宾 菜坝机场','flag':'YBP'},
                {'name':'天津 天津 滨海国际机场','flag':'TSN'},
                {'name':'西藏 昌都 昌都马草机场','flag':'BPX'},
                {'name':'西藏 拉萨 贡嘎国际机场','flag':'LXA'},
                {'name':'新疆 阿克苏 温宿机场','flag':'AKU'},
                {'name':'新疆 富蕴 可可托托海机场','flag':'FYN'},
                {'name':'新疆 哈密 哈密机场','flag':'HMI'},
                {'name':'新疆 和田 和田机场','flag':'HTN'},
                {'name':'新疆 且末 且末机场','flag':'IQM'},
                {'name':'新疆 库车 库车机场','flag':'KCA'},
                {'name':'新疆 喀什 喀什机场','flag':'KHG'},
                {'name':'新疆 库尔勒 库尔勒机场','flag':'KRL'},
                {'name':'新疆 克拉玛依 克拉玛依机场','flag':'KRY'},
                {'name':'新疆 塔城 塔城机场','flag':'TCG'},
                {'name':'新疆 乌鲁木齐 地窝堡国际机场','flag':'URC'},
                {'name':'新疆 伊宁 伊宁机场','flag':'YIN'},
                {'name':'云南省 保山 保山机场','flag':'BSD'},
                {'name':'云南省 迪庆香格里拉 迪庆机场','flag':'DIG'},
                {'name':'云南省 大理 大理机场','flag':'DLU'},
                {'name':'云南省 西双版纳 景洪机场','flag':'JHG'},
                {'name':'云南省 昆明 长水国际机场','flag':'KMG'},
                {'name':'云南省 丽江 丽江国际机场','flag':'LJG'},
                {'name':'云南省 临沧 临沧机场','flag':'LNJ'},
                {'name':'云南省 德宏芒市 芒市机场','flag':'LUM'},
                {'name':'云南省 思茅 思茅机场','flag':'SYM'},
                {'name':'云南省 昭通 昭通机场','flag':'ZAT'},
                {'name':'浙江省 杭州 萧山国际机场','flag':'HGH'},
                {'name':'浙江省 舟山 普陀山机场','flag':'HSN'},
                {'name':'浙江省 台州/黄岩 路桥机场','flag':'HYN'},
                {'name':'浙江省 衢州 衢州机场','flag':'JUZ'},
                {'name':'浙江省 宁波 栎社国际机场','flag':'NGB'},
                {'name':'浙江省 温州 龙湾国际机场','flag':'WNZ'},
                {'name':'浙江省 义乌 义乌机场','flag':'YIW'},
                {'name':'重庆 重庆 江北国际机场','flag':'CKG'},
                {'name':'香港 香港 香港国际机场','flag':'HKG'},
                {'name':'澳门 澳门 澳门国际机场','flag':'MFM'},
                {'name':'日本 东京 成田机场','flag':'NRT'},
                {'name':'日本 东京 羽田机场','flag':'HND'},
                {'name':'日本 大阪 关西国际机场','flag':'KIX'},
                {'name':'日本 名古屋 名古屋中部国际机场','flag':'NGO'},
                {'name':'日本 福冈 福冈国际机场','flag':'FUK'},
                {'name':'日本 冲绳 那霸机场','flag':'OKA'},
                {'name':'韩国 仁川 仁川国际机场','flag':'ICN'},
                {'name':'韩国 釜山 釜山金海国际机场','flag':'PUS'},
                {'name':'泰国 曼谷 廊曼国际机场','flag':'DMK'},
                {'name':'泰国 普吉岛 普吉国际机场','flag':'HKT'},
                {'name':'越南 胡志明 胡志明市新机场','flag':'SGN'},
                {'name':'新加坡 新加坡 新加坡樟宜国际机场','flag':'SIN'},
                {'name':'马来西亚 吉隆坡 吉隆坡国际机场','flag':'KUL'},
                {'name':'印度 新德里 新德里国际机场','flag':'DEL'},
                {'name':'印度 孟买 孟买迪拜国际机场','flag':'BOM'},
                {'name':'印度 金奈/钦奈/马德拉斯 金奈国际机场','flag':'MAA'},
                {'name':'柬埔寨 金边 金边机场','flag':'PNH'},
                {'name':'孟加拉国 达卡 达卡国际机场','flag':'DAC'},
                {'name':'阿联酋 迪拜 迪拜国际机场','flag':'DXB'},
                {'name':'阿布扎比 阿布扎比国际机场','flag':'AUH'},
                {'name':'沙特阿拉伯 利雅得 哈利德国王国际机场','flag':'RUH'},
                {'name':'沙特阿拉伯 达曼 法赫德国王国际机场','flag':'DMM'},
                {'name':'卡塔尔 多哈 多哈国际机场','flag':'DOH'},
                {'name':'土耳其 伊斯坦布尔 伊斯坦布尔国际机场','flag':'IST'},
                {'name':'土耳其 伊兹密尔 伊兹密尔机场','flag':'IZM'},
                {'name':'伊朗 德黑兰 梅赫拉巴德国际机场','flag':'THR'},
                {'name':'加拿大 渥太华 渥太华国际机场','flag':'YOW'},
                {'name':'加拿大 蒙特利尔 多尔瓦国际机场','flag':'YUL'},
                {'name':'加拿大 温哥华 温哥华国际机场','flag':'YVR'},
                {'name':'加拿大 多伦多 皮尔森国际机场','flag':'YYZ'},
                {'name':'美国 华盛顿 杜勒斯国际机场','flag':'IAD'},
                {'name':'美国 纽约 肯尼迪国际机场','flag':'JFK'},
                {'name':'美国 洛杉矶 洛杉矶国际机场','flag':'LAX'},
                {'name':'美国 芝加哥 奥黑尔国际机场','flag':'ORD'},
                {'name':'美国 波士顿 洛根国际机场','flag':'BOS'},
                {'name':'美国 旧金山 旧金山国际机场','flag':'SFO'},
                {'name':'美国 西雅图 塔科马国际机场','flag':'SEA'},
                {'name':'美国 丹佛 丹佛国际机场','flag':'DEN'},
                {'name':'美国 拉斯维加斯 麦卡伦国际机场','flag':'LAS'},
                {'name':'美国 克里夫兰 克里夫兰国际机场','flag':'CLE'},
                {'name':'美国 亚特兰大 亚特兰大国际机场','flag':'ATL'},
                {'name':'美国 底特律 底特律都会机场','flag':'DTW'},
                {'name':'美国 达拉斯 沃斯堡机场','flag':'DFW'},
                {'name':'美国 迈阿密 迈阿密国际机场','flag':'MIA'},
                {'name':'美国 休斯敦 布什国际机场','flag':'IAH'},
                {'name':'美国 奥兰多 奥兰多国际机场','flag':'MCO'},
                {'name':'美国 凤凰城 天港国际机场','flag':'PHX'},
                {'name':'美国 费城 费城国际机场','flag':'PHL'},
                {'name':'美国 盐湖城 盐湖城国际机场','flag':'SLC'},
                {'name':'意大利 罗马 菲乌米奇诺机场','flag':'FCO'},
                {'name':'意大利 米兰 马尔蓬萨机场','flag':'MXP'},
                {'name':'意大利 威尼斯 威尼斯机场','flag':'VCE'},
                {'name':'意大利 那不勒斯 那不勒斯机场','flag':'NAP'},
                {'name':'意大利 佛罗伦萨 佛罗伦萨机场','flag':'FLR'},
                {'name':'意大利 热那亚 热那亚机场','flag':'GOA'},
                {'name':'意大利 都灵 都灵机场','flag':'TRN'},
                {'name':'意大利 比萨 比萨机场','flag':'PIS'},
                {'name':'捷克 布拉格 鲁济涅机场','flag':'PRG'},
                {'name':'斯洛伐克 布拉迪斯拉发 斯特法尼科机场','flag':'BTS'},
                {'name':'匈牙利 布达佩斯 费里海吉机场','flag':'BUD'},
                {'name':'卢森堡 卢森堡 卢森堡国际机场','flag':'LUX'},
                {'name':'奥地利 维也纳 施韦夏特机场','flag':'VIE'},
                {'name':'罗马尼亚 布加勒斯特 布加勒斯特机场','flag':'BUH'},
                {'name':'克罗地亚 萨格勒布 萨格勒布机场','flag':'ZAG'},
                {'name':'波兰 华沙 奥肯切机场','flag':'WAW'},
                {'name':'希腊 雅典 雅典国际机场','flag':'ATH'},
                {'name':'俄罗斯 莫斯科	谢列梅捷沃机场','flag':'SVO'},
                {'name':'圣彼得堡 普尔科夫机场','flag':'LED'},
                {'name':'保加利亚 索菲亚	索菲亚机场','flag':'SOF'},
                {'name':'乌克兰 基辅 波里斯琥珀尔','flag':'KBP'},
                {'name':'乌克兰 基辅 茹良尼机场','flag':'IEV'},
                {'name':'英格兰 伦敦 希思罗机场','flag':'LHR'},
                {'name':'英格兰 伦敦 卢顿机场','flag':'LTN'},
                {'name':'英格兰 伦敦 盖特威克机场','flag':'LGW'},
                {'name':'英格兰 曼彻斯特 曼彻斯特国际机场','flag':'MAN'},
                {'name':'苏格兰 爱丁堡 爱丁堡机场','flag':'EDI'},
                {'name':'爱尔兰 都柏林 都柏林国际机场','flag':'DUB'},
                {'name':'荷兰 阿姆斯特丹 西佛尔国际机场','flag':'AMS'},
                {'name':'荷兰 鹿特丹 鹿特丹国际机场','flag':'RTM'},
                {'name':'荷兰 埃因霍温 埃因霍温国际机场','flag':'EIN'},
                {'name':'丹麦 哥本哈根 斯楚普国际机场','flag':'CPH'},
                {'name':'瑞典 斯德哥尔摩 阿兰达国际机场','flag':'ARN'},
                {'name':'挪威 奥斯陆 加勒穆恩国际机场','flag':'OSL'},
                {'name':'芬兰 赫尔辛基 万塔国际机场','flag':'HEL'},
                {'name':'比利时 布鲁塞尔 布鲁塞尔国际机场','flag':'BRU'},
                {'name':'德国 慕尼黑 慕尼黑机场','flag':'MUC'},
                {'name':'德国 柏林 泰格尔机场','flag':'TXL'},
                {'name':'德国 法兰克福 莱茵美应国际机场','flag':'FRA'},
                {'name':'德国 不莱梅 不莱梅机场','flag':'BRE'},
                {'name':'德国 斯图加特 斯图加特机场','flag':'STR'},
                {'name':'德国 汉堡 汉堡国际机场','flag':'HAM'},
                {'name':'德国 科隆 科隆机场','flag':'CGN'},
                {'name':'德国 哈恩 哈恩国际机场','flag':'HNN'},
                {'name':'法国 巴黎 戴高乐机场','flag':'CDG'},
                {'name':'法国 里尔 里尔国际机场','flag':'LIL'},
                {'name':'法国 马赛 马赛机场','flag':'MRS'},
                {'name':'法国 里昂 里昂机场','flag':'LYS'},
                {'name':'瑞士 苏黎世 苏黎世国际机场','flag':'ZRH'},
                {'name':'瑞士 日内瓦 日内瓦国际机场','flag':'GVA'},
                {'name':'西班牙 马德里 巴拉哈斯机场','flag':'MAD'},
                {'name':'西班牙 巴塞罗那 安普拉特机场','flag':'BCN'},
                {'name':'西班牙 瓦伦西亚 瓦伦西亚国际机场','flag':'VLC'},
                {'name':'葡萄牙 里斯本 里斯本机场','flag':'LIS'},
                {'name':'葡萄牙 波尔图 奥波多机场','flag':'OPO'},
                {'name':'墨西哥 墨西哥城 贝尼托·胡亚雷斯国际机场','flag':'MEX'},
                {'name':'智利 圣地亚哥 圣地亚哥国际机场','flag':'SCL'},
                {'name':'秘鲁 利马 利马国际机场','flag':'LIM'},
                {'name':'巴拿马 巴拿马城 巴拿马城机场','flag':'PTY'},
                {'name':'哥斯达黎加 圣何塞 圣何塞机场','flag':'SJO'},
                {'name':'委内瑞拉 加拉加斯 西蒙玻利瓦尔国际机场','flag':'CCS'},
                {'name':'阿根廷 布宜诺斯艾利斯 埃塞萨国际机场','flag':'EZE'},
                {'name':'巴西 圣保罗 圣保罗国际机场','flag':'GRU'},
                {'name':'巴西 圣保罗 坎皮纳斯国际机场','flag':'VCP'},
                {'name':'巴西 里约热内卢 里约热内卢国际机场','flag':'GIG'},
                {'name':'巴西 库里蒂巴 库里蒂巴国际机场','flag':'CWB'},
                {'name':'澳大利亚 堪培拉 堪培拉机场','flag':'CBR'},
                {'name':'澳大利亚 墨尔本 墨尔本国际机场','flag':'MEL'},
                {'name':'澳大利亚 悉尼 悉尼金斯福国际机场','flag':'SYD'},
                {'name':'新西兰 惠灵顿 惠灵顿机场','flag':'WLG'},
                {'name':'埃及 开罗 开罗国际机场','flag':'CAI'},
                {'name':'塞内加尔 达喀尔 达喀尔机场','flag':'DKR'},
                {'name':'南非 约翰内斯堡 约翰内斯堡国际机场','flag':'JNB'}];
        }


        return {
            getIATAJson: getIATAJson
        }

    });